# 기본(default) 룰이 아닌 룰들을 활성화
opt_in_rules:
    - sorted_imports
    
line_length:
  warning: 250
  error: 300

function_body_length:
    warning: 80
    error: 120

disabled_rules:
  - force_cast
  - blanket_disable_command
