name: MLS CI

permissions:
  contents: write  # ✨ 추가: Push를 위한 권한

on:
  pull_request:
    branches: [main, dev]

jobs:
  autocorrect:
    name: 🤖 Autocorrect Workflow
    runs-on: macos-15
    if: github.actor != 'github-actions[bot]' && github.base_ref == 'dev'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: 🛠️ Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode_16.2.app

      - name: ⬇️ Install SwiftLint
        run: brew install swiftlint

      - name: 🎨 Run SwiftLint Autocorrect
        run: swiftlint --fix

      - name: 🚀 Commit and Push Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git fetch origin "${GITHUB_HEAD_REF}:${GITHUB_HEAD_REF}"
          git checkout "${GITHUB_HEAD_REF}"

          BRANCH_NAME="${GITHUB_HEAD_REF}"
          if [[ "$BRANCH_NAME" =~ \#([0-9]+) ]]; then
            ISSUE_NUMBER="${BASH_REMATCH[1]}"
          else
            ISSUE_NUMBER=""
          fi

          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "style/#${ISSUE_NUMBER}: Apply SwiftLint autocorrect"
            git push --set-upstream origin "${GITHUB_HEAD_REF}"
          else
            echo "No changes to commit"
          fi
